[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
db_name = financa_staging
dbfilter = ^financa_staging$
list_db = False
proxy_mode = True
workers = 0
max_cron_threads = 1
limit_memory_soft = 1342177280
limit_memory_hard = 1610612736
smtp_server = 127.0.0.1
smtp_port = 9
smtp_ssl = False
email_from = False
